[package]
name = "quantamax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.36"
rand = "0.8.5"
draw = "0.3.0"
cond_utils = "0.1.0"
cuda_std = "0.2.2"